export const countries = [
    { value: '+93', label: 'Afghanistan (+93)', flag: '/icons/countries/af.svg' },
    { value: '+355', label: 'Albania (+355)', flag: '/icons/countries/al.svg' },
    { value: '+213', label: 'Algeria (+213)', flag: '/icons/countries/dz.svg' },
    { value: '+1', label: 'American Samoa (+1)', flag: '/icons/countries/as.svg' },
    { value: '+376', label: 'Andorra (+376)', flag: '/icons/countries/ad.svg' },
    { value: '+244', label: 'Angola (+244)', flag: '/icons/countries/ao.svg' },
    { value: '+1', label: 'Anguilla (+1)', flag: '/icons/countries/ai.svg' },
    { value: '+1', label: 'Antigua and Barbuda (+1)', flag: '/icons/countries/ag.svg' },
    { value: '+54', label: 'Argentina (+54)', flag: '/icons/countries/ar.svg' },
    { value: '+374', label: 'Armenia (+374)', flag: '/icons/countries/am.svg' },
    { value: '+297', label: 'Aruba (+297)', flag: '/icons/countries/aw.svg' },
    { value: '+61', label: 'Australia (+61)', flag: '/icons/countries/au.svg' },
    { value: '+43', label: 'Austria (+43)', flag: '/icons/countries/at.svg' },
    { value: '+994', label: 'Azerbaijan (+994)', flag: '/icons/countries/az.svg' },
    { value: '+1', label: 'Bahamas (+1)', flag: '/icons/countries/bs.svg' },
    { value: '+973', label: 'Bahrain (+973)', flag: '/icons/countries/bh.svg' },
    { value: '+880', label: 'Bangladesh (+880)', flag: '/icons/countries/bd.svg' },
    { value: '+1', label: 'Barbados (+1)', flag: '/icons/countries/bb.svg' },
    { value: '+375', label: 'Belarus (+375)', flag: '/icons/countries/by.svg' },
    { value: '+32', label: 'Belgium (+32)', flag: '/icons/countries/be.svg' },
    { value: '+501', label: 'Belize (+501)', flag: '/icons/countries/bz.svg' },
    { value: '+229', label: 'Benin (+229)', flag: '/icons/countries/bj.svg' },
    { value: '+1', label: 'Bermuda (+1)', flag: '/icons/countries/bm.svg' },
    { value: '+975', label: 'Bhutan (+975)', flag: '/icons/countries/bt.svg' },
    { value: '+591', label: 'Bolivia (+591)', flag: '/icons/countries/bo.svg' },
    { value: '+387', label: 'Bosnia and Herzegovina (+387)', flag: '/icons/countries/ba.svg' },
    { value: '+267', label: 'Botswana (+267)', flag: '/icons/countries/bw.svg' },
    { value: '+55', label: 'Brazil (+55)', flag: '/icons/countries/br.svg' },
    { value: '+246', label: 'British Indian Ocean Territory (+246)', flag: '/icons/countries/io.svg' },
    { value: '+1', label: 'British Virgin Islands (+1)', flag: '/icons/countries/vg.svg' },
    { value: '+673', label: 'Brunei (+673)', flag: '/icons/countries/bn.svg' },
    { value: '+359', label: 'Bulgaria (+359)', flag: '/icons/countries/bg.svg' },
    { value: '+226', label: 'Burkina Faso (+226)', flag: '/icons/countries/bf.svg' },
    { value: '+257', label: 'Burundi (+257)', flag: '/icons/countries/bi.svg' },
    { value: '+855', label: 'Cambodia (+855)', flag: '/icons/countries/kh.svg' },
    { value: '+237', label: 'Cameroon (+237)', flag: '/icons/countries/cm.svg' },
    { value: '+1', label: 'Canada (+1)', flag: '/icons/countries/ca.svg' },
    { value: '+238', label: 'Cape Verde (+238)', flag: '/icons/countries/cv.svg' },
    { value: '+1', label: 'Cayman Islands (+1)', flag: '/icons/countries/ky.svg' },
    { value: '+236', label: 'Central African Republic (+236)', flag: '/icons/countries/cf.svg' },
    { value: '+235', label: 'Chad (+235)', flag: '/icons/countries/td.svg' },
    { value: '+56', label: 'Chile (+56)', flag: '/icons/countries/cl.svg' },
    { value: '+86', label: 'China (+86)', flag: '/icons/countries/cn.svg' },
    { value: '+61', label: 'Christmas Island (+61)', flag: '/icons/countries/cx.svg' },
    { value: '+61', label: 'Cocos Islands (+61)', flag: '/icons/countries/cc.svg' },
    { value: '+57', label: 'Colombia (+57)', flag: '/icons/countries/co.svg' },
    { value: '+269', label: 'Comoros (+269)', flag: '/icons/countries/km.svg' },
    { value: '+682', label: 'Cook Islands (+682)', flag: '/icons/countries/ck.svg' },
    { value: '+506', label: 'Costa Rica (+506)', flag: '/icons/countries/cr.svg' },
    { value: '+385', label: 'Croatia (+385)', flag: '/icons/countries/hr.svg' },
    { value: '+53', label: 'Cuba (+53)', flag: '/icons/countries/cu.svg' },
    { value: '+599', label: 'Curacao (+599)', flag: '/icons/countries/cw.svg' },
    { value: '+357', label: 'Cyprus (+357)', flag: '/icons/countries/cy.svg' },
    { value: '+420', label: 'Czech Republic (+420)', flag: '/icons/countries/cz.svg' },
    { value: '+243', label: 'Democratic Republic of the Congo (+243)', flag: '/icons/countries/cd.svg' },
    { value: '+45', label: 'Denmark (+45)', flag: '/icons/countries/dk.svg' },
    { value: '+253', label: 'Djibouti (+253)', flag: '/icons/countries/dj.svg' },
    { value: '+1', label: 'Dominica (+1)', flag: '/icons/countries/dm.svg' },
    { value: '+1', label: 'Dominican Republic (+1)', flag: '/icons/countries/do.svg' },
    { value: '+593', label: 'Ecuador (+593)', flag: '/icons/countries/ec.svg' },
    { value: '+20', label: 'Egypt (+20)', flag: '/icons/countries/eg.svg' },
    { value: '+503', label: 'El Salvador (+503)', flag: '/icons/countries/sv.svg' },
    { value: '+240', label: 'Equatorial Guinea (+240)', flag: '/icons/countries/gq.svg' },
    { value: '+291', label: 'Eritrea (+291)', flag: '/icons/countries/er.svg' },
    { value: '+372', label: 'Estonia (+372)', flag: '/icons/countries/ee.svg' },
    { value: '+251', label: 'Ethiopia (+251)', flag: '/icons/countries/et.svg' },
    { value: '+500', label: 'Falkland Islands (+500)', flag: '/icons/countries/fk.svg' },
    { value: '+298', label: 'Faroe Islands (+298)', flag: '/icons/countries/fo.svg' },
    { value: '+679', label: 'Fiji (+679)', flag: '/icons/countries/fj.svg' },
    { value: '+358', label: 'Finland (+358)', flag: '/icons/countries/fi.svg' },
    { value: '+33', label: 'France (+33)', flag: '/icons/countries/fr.svg' },
    { value: '+594', label: 'French Guiana (+594)', flag: '/icons/countries/gf.svg' },
    { value: '+689', label: 'French Polynesia (+689)', flag: '/icons/countries/pf.svg' },
    { value: '+241', label: 'Gabon (+241)', flag: '/icons/countries/ga.svg' },
    { value: '+220', label: 'Gambia (+220)', flag: '/icons/countries/gm.svg' },
    { value: '+995', label: 'Georgia (+995)', flag: '/icons/countries/ge.svg' },
    { value: '+49', label: 'Germany (+49)', flag: '/icons/countries/de.svg' },
    { value: '+233', label: 'Ghana (+233)', flag: '/icons/countries/gh.svg' },
    { value: '+350', label: 'Gibraltar (+350)', flag: '/icons/countries/gi.svg' },
    { value: '+30', label: 'Greece (+30)', flag: '/icons/countries/gr.svg' },
    { value: '+299', label: 'Greenland (+299)', flag: '/icons/countries/gl.svg' },
    { value: '+1 473', label: 'Grenada (+1 473)', flag: '/icons/countries/gd.svg' },
    { value: '+590', label: 'Guadeloupe (+590)', flag: '/icons/countries/gp.svg' },
    { value: '+1 671', label: 'Guam (+1 671)', flag: '/icons/countries/gu.svg' },
    { value: '+502', label: 'Guatemala (+502)', flag: '/icons/countries/gt.svg' },
    { value: '+44', label: 'Guernsey (+44)', flag: '/icons/countries/gg.svg' },
    { value: '+224', label: 'Guinea (+224)', flag: '/icons/countries/gn.svg' },
    { value: '+245', label: 'Guinea-Bissau (+245)', flag: '/icons/countries/gw.svg' },
    { value: '+592', label: 'Guyana (+592)', flag: '/icons/countries/gy.svg' },
    { value: '+509', label: 'Haiti (+509)', flag: '/icons/countries/ht.svg' },
    { value: '+504', label: 'Honduras (+504)', flag: '/icons/countries/hn.svg' },
    { value: '+852', label: 'Hong Kong (+852)', flag: '/icons/countries/hk.svg' },
    { value: '+36', label: 'Hungary (+36)', flag: '/icons/countries/hu.svg' },
    { value: '+354', label: 'Iceland (+354)', flag: '/icons/countries/is.svg' },
    { value: '+91', label: 'India (+91)', flag: '/icons/countries/in.svg' },
    { value: '+62', label: 'Indonesia (+62)', flag: '/icons/countries/id.svg' },
    { value: '+98', label: 'Iran (+98)', flag: '/icons/countries/ir.svg' },
    { value: '+964', label: 'Iraq (+964)', flag: '/icons/countries/iq.svg' },
    { value: '+353', label: 'Ireland (+353)', flag: '/icons/countries/ie.svg' },
    { value: '+44', label: 'Isle of Man (+44)', flag: '/icons/countries/im.svg' },
    { value: '+972', label: 'Israel (+972)', flag: '/icons/countries/il.svg' },
    { value: '+39', label: 'Italy (+39)', flag: '/icons/countries/it.svg' },
    { value: '+1 876', label: 'Jamaica (+1 876)', flag: '/icons/countries/jm.svg' },
    { value: '+81', label: 'Japan (+81)', flag: '/icons/countries/jp.svg' },
    { value: '+44', label: 'Jersey (+44)', flag: '/icons/countries/je.svg' },
    { value: '+962', label: 'Jordan (+962)', flag: '/icons/countries/jo.svg' },
    { value: '+7 7', label: 'Kazakhstan (+7 7)', flag: '/icons/countries/kz.svg' },
    { value: '+254', label: 'Kenya (+254)', flag: '/icons/countries/ke.svg' },
    { value: '+686', label: 'Kiribati (+686)', flag: '/icons/countries/ki.svg' },
    { value: '+383', label: 'Kosovo (+383)', flag: '/icons/countries/xk.svg' },
    { value: '+965', label: 'Kuwait (+965)', flag: '/icons/countries/kw.svg' },
    { value: '+996', label: 'Kyrgyzstan (+996)', flag: '/icons/countries/kg.svg' },
    { value: '+856', label: 'Laos (+856)', flag: '/icons/countries/la.svg' },
    { value: '+371', label: 'Latvia (+371)', flag: '/icons/countries/lv.svg' },
    { value: '+961', label: 'Lebanon (+961)', flag: '/icons/countries/lb.svg' },
    { value: '+266', label: 'Lesotho (+266)', flag: '/icons/countries/ls.svg' },
    { value: '+231', label: 'Liberia (+231)', flag: '/icons/countries/lr.svg' },
    { value: '+218', label: 'Libya (+218)', flag: '/icons/countries/ly.svg' },
    { value: '+423', label: 'Liechtenstein (+423)', flag: '/icons/countries/li.svg' },
    { value: '+370', label: 'Lithuania (+370)', flag: '/icons/countries/lt.svg' },
    { value: '+352', label: 'Luxembourg (+352)', flag: '/icons/countries/lu.svg' },
    { value: '+853', label: 'Macao (+853)', flag: '/icons/countries/mo.svg' },
    { value: '+389', label: 'Macedonia (+389)', flag: '/icons/countries/mk.svg' },
    { value: '+261', label: 'Madagascar (+261)', flag: '/icons/countries/mg.svg' },
    { value: '+265', label: 'Malawi (+265)', flag: '/icons/countries/mw.svg' },
    { value: '+60', label: 'Malaysia (+60)', flag: '/icons/countries/my.svg' },
    { value: '+960', label: 'Maldives (+960)', flag: '/icons/countries/mv.svg' },
    { value: '+223', label: 'Mali (+223)', flag: '/icons/countries/ml.svg' },
    { value: '+356', label: 'Malta (+356)', flag: '/icons/countries/mt.svg' },
    { value: '+692', label: 'Marshall Islands (+692)', flag: '/icons/countries/mh.svg' },
    { value: '+596', label: 'Martinique (+596)', flag: '/icons/countries/mq.svg' },
    { value: '+222', label: 'Mauritania (+222)', flag: '/icons/countries/mr.svg' },
    { value: '+230', label: 'Mauritius (+230)', flag: '/icons/countries/mu.svg' },
    { value: '+262', label: 'Mayotte (+262)', flag: '/icons/countries/yt.svg' },
    { value: '+52', label: 'Mexico (+52)', flag: '/icons/countries/mx.svg' },
    { value: '+691', label: 'Micronesia (+691)', flag: '/icons/countries/fm.svg' },
    { value: '+373', label: 'Moldova (+373)', flag: '/icons/countries/md.svg' },
    { value: '+377', label: 'Monaco (+377)', flag: '/icons/countries/mc.svg' },
    { value: '+976', label: 'Mongolia (+976)', flag: '/icons/countries/mn.svg' },
    { value: '+382', label: 'Montenegro (+382)', flag: '/icons/countries/me.svg' },
    { value: '+1 664', label: 'Montserrat (+1 664)', flag: '/icons/countries/ms.svg' },
    { value: '+212', label: 'Morocco (+212)', flag: '/icons/countries/ma.svg' },
    { value: '+258', label: 'Mozambique (+258)', flag: '/icons/countries/mz.svg' },
    { value: '+95', label: 'Myanmar (+95)', flag: '/icons/countries/mm.svg' },
    { value: '+264', label: 'Namibia (+264)', flag: '/icons/countries/na.svg' },
    { value: '+674', label: 'Nauru (+674)', flag: '/icons/countries/nr.svg' },
    { value: '+977', label: 'Nepal (+977)', flag: '/icons/countries/np.svg' },
    { value: '+31', label: 'Netherlands (+31)', flag: '/icons/countries/nl.svg' },
    { value: '+599', label: 'Netherlands Antilles (+599)', flag: '/icons/countries/an.svg' },
    { value: '+687', label: 'New Caledonia (+687)', flag: '/icons/countries/nc.svg' },
    { value: '+64', label: 'New Zealand (+64)', flag: '/icons/countries/nz.svg' },
    { value: '+505', label: 'Nicaragua (+505)', flag: '/icons/countries/ni.svg' },
    { value: '+227', label: 'Niger (+227)', flag: '/icons/countries/ne.svg' },
    { value: '+234', label: 'Nigeria (+234)', flag: '/icons/countries/ng.svg' },
    { value: '+683', label: 'Niue (+683)', flag: '/icons/countries/nu.svg' },
    { value: '+672', label: 'Norfolk Island (+672)', flag: '/icons/countries/nf.svg' },
    { value: '+1 670', label: 'Northern Mariana Islands (+1 670)', flag: '/icons/countries/mp.svg' },
    { value: '+47', label: 'Norway (+47)', flag: '/icons/countries/no.svg' },
    { value: '+968', label: 'Oman (+968)', flag: '/icons/countries/om.svg' },
    { value: '+92', label: 'Pakistan (+92)', flag: '/icons/countries/pk.svg' },
    { value: '+680', label: 'Palau (+680)', flag: '/icons/countries/pw.svg' },
    { value: '+970', label: 'Palestine (+970)', flag: '/icons/countries/ps.svg' },
    { value: '+507', label: 'Panama (+507)', flag: '/icons/countries/pa.svg' },
    { value: '+675', label: 'Papua New Guinea (+675)', flag: '/icons/countries/pg.svg' },
    { value: '+595', label: 'Paraguay (+595)', flag: '/icons/countries/py.svg' },
    { value: '+51', label: 'Peru (+51)', flag: '/icons/countries/pe.svg' },
    { value: '+63', label: 'Philippines (+63)', flag: '/icons/countries/ph.svg' },
    { value: '+48', label: 'Poland (+48)', flag: '/icons/countries/pl.svg' },
    { value: '+351', label: 'Portugal (+351)', flag: '/icons/countries/pt.svg' },
    { value: '+1 787', label: 'Puerto Rico (+1 787)', flag: '/icons/countries/pr.svg' },
    { value: '+974', label: 'Qatar (+974)', flag: '/icons/countries/qa.svg' },
    { value: '+262', label: 'Réunion (+262)', flag: '/icons/countries/re.svg' },
    { value: '+40', label: 'Romania (+40)', flag: '/icons/countries/ro.svg' },
    { value: '+7', label: 'Russia (+7)', flag: '/icons/countries/ru.svg' },
    { value: '+250', label: 'Rwanda (+250)', flag: '/icons/countries/rw.svg' },
    { value: '+590', label: 'Saint Barthélemy (+590)', flag: '/icons/countries/bl.svg' },
    { value: '+290', label: 'Saint Helena (+290)', flag: '/icons/countries/sh.svg' },
    { value: '+1 869', label: 'Saint Kitts and Nevis (+1 869)', flag: '/icons/countries/kn.svg' },
    { value: '+1 758', label: 'Saint Lucia (+1 758)', flag: '/icons/countries/lc.svg' },
    { value: '+590', label: 'Saint Martin (+590)', flag: '/icons/countries/mf.svg' },
    { value: '+508', label: 'Saint Pierre and Miquelon (+508)', flag: '/icons/countries/pm.svg' },
    { value: '+1 784', label: 'Saint Vincent and the Grenadines (+1 784)', flag: '/icons/countries/vc.svg' },
    { value: '+685', label: 'Samoa (+685)', flag: '/icons/countries/ws.svg' },
    { value: '+378', label: 'San Marino (+378)', flag: '/icons/countries/sm.svg' },
    { value: '+239', label: 'São Tomé and Príncipe (+239)', flag: '/icons/countries/st.svg' },
    { value: '+966', label: 'Saudi Arabia (+966)', flag: '/icons/countries/sa.svg' },
    { value: '+221', label: 'Senegal (+221)', flag: '/icons/countries/sn.svg' },
    { value: '+381', label: 'Serbia (+381)', flag: '/icons/countries/rs.svg' },
    { value: '+248', label: 'Seychelles (+248)', flag: '/icons/countries/sc.svg' },
    { value: '+232', label: 'Sierra Leone (+232)', flag: '/icons/countries/sl.svg' },
    { value: '+65', label: 'Singapore (+65)', flag: '/icons/countries/sg.svg' },
    { value: '+421', label: 'Slovakia (+421)', flag: '/icons/countries/sk.svg' },
    { value: '+386', label: 'Slovenia (+386)', flag: '/icons/countries/si.svg' },
    { value: '+677', label: 'Solomon Islands (+677)', flag: '/icons/countries/sb.svg' },
    { value: '+252', label: 'Somalia (+252)', flag: '/icons/countries/so.svg' },
    { value: '+27', label: 'South Africa (+27)', flag: '/icons/countries/za.svg' },
    { value: '+500', label: 'South Georgia and the South Sandwich Islands (+500)', flag: '/icons/countries/gs.svg' },
    { value: '+82', label: 'South Korea (+82)', flag: '/icons/countries/kr.svg' },
    { value: '+211', label: 'South Sudan (+211)', flag: '/icons/countries/ss.svg' },
    { value: '+34', label: 'Spain (+34)', flag: '/icons/countries/es.svg' },
    { value: '+94', label: 'Sri Lanka (+94)', flag: '/icons/countries/lk.svg' },
    { value: '+249', label: 'Sudan (+249)', flag: '/icons/countries/sd.svg' },
    { value: '+597', label: 'Suriname (+597)', flag: '/icons/countries/sr.svg' },
    { value: '+47', label: 'Svalbard and Jan Mayen (+47)', flag: '/icons/countries/sj.svg' },
    { value: '+268', label: 'Swaziland (+268)', flag: '/icons/countries/sz.svg' },
    { value: '+46', label: 'Sweden (+46)', flag: '/icons/countries/se.svg' },
    { value: '+41', label: 'Switzerland (+41)', flag: '/icons/countries/ch.svg' },
    { value: '+963', label: 'Syria (+963)', flag: '/icons/countries/sy.svg' },
    { value: '+886', label: 'Taiwan (+886)', flag: '/icons/countries/tw.svg' },
    { value: '+992', label: 'Tajikistan (+992)', flag: '/icons/countries/tj.svg' },
    { value: '+255', label: 'Tanzania (+255)', flag: '/icons/countries/tz.svg' },
    { value: '+66', label: 'Thailand (+66)', flag: '/icons/countries/th.svg' },
    { value: '+670', label: 'Timor-Leste (+670)', flag: '/icons/countries/tl.svg' },
    { value: '+228', label: 'Togo (+228)', flag: '/icons/countries/tg.svg' },
    { value: '+690', label: 'Tokelau (+690)', flag: '/icons/countries/tk.svg' },
    { value: '+676', label: 'Tonga (+676)', flag: '/icons/countries/to.svg' },
    { value: '+1 868', label: 'Trinidad and Tobago (+1 868)', flag: '/icons/countries/tt.svg' },
    { value: '+216', label: 'Tunisia (+216)', flag: '/icons/countries/tn.svg' },
    { value: '+90', label: 'Turkey (+90)', flag: '/icons/countries/tr.svg' },
    { value: '+993', label: 'Turkmenistan (+993)', flag: '/icons/countries/tm.svg' },
    { value: '+1 649', label: 'Turks and Caicos Islands (+1 649)', flag: '/icons/countries/tc.svg' },
    { value: '+688', label: 'Tuvalu (+688)', flag: '/icons/countries/tv.svg' },
    { value: '+1 340', label: 'U.S. Virgin Islands (+1 340)', flag: '/icons/countries/vi.svg' },
    { value: '+256', label: 'Uganda (+256)', flag: '/icons/countries/ug.svg' },
    { value: '+380', label: 'Ukraine (+380)', flag: '/icons/countries/ua.svg' },
    { value: '+971', label: 'United Arab Emirates (+971)', flag: '/icons/countries/ae.svg' },
    { value: '+44', label: 'United Kingdom (+44)', flag: '/icons/countries/gb.svg' },
    { value: '+1', label: 'United States (+1)', flag: '/icons/countries/us.svg' },
    { value: '+598', label: 'Uruguay (+598)', flag: '/icons/countries/uy.svg' },
    { value: '+998', label: 'Uzbekistan (+998)', flag: '/icons/countries/uz.svg' },
    { value: '+678', label: 'Vanuatu (+678)', flag: '/icons/countries/vu.svg' },
    { value: '+379', label: 'Vatican City (+379)', flag: '/icons/countries/va.svg' },
    { value: '+58', label: 'Venezuela (+58)', flag: '/icons/countries/ve.svg' },
    { value: '+84', label: 'Vietnam (+84)', flag: '/icons/countries/vn.svg' },
    { value: '+681', label: 'Wallis and Futuna (+681)', flag: '/icons/countries/wf.svg' },
    { value: '+212', label: 'Western Sahara (+212)', flag: '/icons/countries/eh.svg' },
    { value: '+967', label: 'Yemen (+967)', flag: '/icons/countries/ye.svg' },
    { value: '+260', label: 'Zambia (+260)', flag: '/icons/countries/zm.svg' },
    { value: '+263', label: 'Zimbabwe (+263)', flag: '/icons/countries/zw.svg' },
]